version: '3.8'

services:
  ms1:
    build:
      context: ./microservicio1
    container_name: ms1
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=pacientes_db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=172.31.21.115   # ← IP privada EC2 de PostgreSQL
      - DB_PORT=5432

  ms2:
    build:
      context: ./microservicio2
    container_name: ms2
    ports:
      - "3000:3000"
    environment:
      DB_HOST: "172.31.21.115"
      DB_PORT: "3307"
      DB_USERNAME: "root"
      DB_PASSWORD: "utec"
      DB_NAME: "consultasdb"

  ms3:
    build:
      context: ./microservicio3
    container_name: ms3
    ports:
      - "5000:80"
    environment:
      - Mongo__Connection=mongodb://172.31.21.115:27017
      - Mongo__Database=VetImagesDb

  ms4:
    build:
      context: ./microservicio4
    container_name: ms4
    ports:
      - "8004:8004"
    depends_on:
      - ms1
      - ms2
      - ms3
    env_file:
      - ./microservicio4/.env

networks:
  default:
    driver: bridge
