version: '3.9'
services:
  microservicio1:
    build: ./microservicio1
    ports:
      - "8000:8000"
    container_name: ms1
    networks:
      - red_microservicios

  microservicio2:
    build: ./microservicio2
    ports:
      - "3002:3000"
    container_name: ms2
    networks:
      - red_microservicios
    depends_on:
      - microservicio1

  microservicio3:
    build: ./microservicio3
    ports:
      - "3003:80"
    container_name: ms3
    networks:
      - red_microservicios
    depends_on:
      - microservicio2
      - mongo

  microservicio4:
    build: ./microservicio4
    ports:
      - "8004:8000"
    container_name: ms4
    networks:
      - red_microservicios
    depends_on:
      - microservicio3

  mysql:
    image: mysql:8.0
    container_name: mysql_c
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: utec
      MYSQL_DATABASE: consultasdb
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - red_microservicios

  mongo:
    image: mongo
    container_name: mongo_c
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - red_microservicios

  postgres:
    image: postgres:13
    container_name: postgres_c
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pacientes_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - red_microservicios

volumes:
  mysql_data:
  mongo_data:
  postgres_data:

networks:
  red_microservicios:
    driver: bridge
