version: '3.4'

services:
  vetimages:
    build: .
    ports:
      - "3003:80"
    environment:
      - MONGO_HOST=172.31.21.115    # IP de la EC2 que contiene MongoDB
      - MONGO_PORT=27017
