version: '3.4'

services:
  vetimages:
    build: .
    ports:
      - "3003:80"
    environment:
      - MONGO_HOST=192.168.1.102    # IP de la EC2 que contiene MongoDB
      - MONGO_PORT=27017
