version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DB_NAME: pacientes_db
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: 172.31.21.115  # <- IP privada de tu EC2 que tiene PostgreSQL
      DB_PORT: 5432
